// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/proto/message.proto
// Protobuf Java Version: 4.27.3

public final class MessageProtoBuffer {
    private MessageProtoBuffer() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public interface MessageOrBuilder extends
            // @@protoc_insertion_point(interface_extends:Message)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <pre>
         * Nome do emissor
         * </pre>
         *
         * <code>string sender = 1;</code>
         * 
         * @return The sender.
         */
        java.lang.String getSender();

        /**
         * <pre>
         * Nome do emissor
         * </pre>
         *
         * <code>string sender = 1;</code>
         * 
         * @return The bytes for sender.
         */
        com.google.protobuf.ByteString getSenderBytes();

        /**
         * <pre>
         * Data de envio
         * </pre>
         *
         * <code>string date = 2;</code>
         * 
         * @return The date.
         */
        java.lang.String getDate();

        /**
         * <pre>
         * Data de envio
         * </pre>
         *
         * <code>string date = 2;</code>
         * 
         * @return The bytes for date.
         */
        com.google.protobuf.ByteString getDateBytes();

        /**
         * <pre>
         * Hora de envio
         * </pre>
         *
         * <code>string hour = 3;</code>
         * 
         * @return The hour.
         */
        java.lang.String getHour();

        /**
         * <pre>
         * Hora de envio
         * </pre>
         *
         * <code>string hour = 3;</code>
         * 
         * @return The bytes for hour.
         */
        com.google.protobuf.ByteString getHourBytes();

        /**
         * <pre>
         * Informa o nome do grupo, se a mensagem for para um grupo
         * </pre>
         *
         * <code>string group = 4;</code>
         * 
         * @return The group.
         */
        java.lang.String getGroup();

        /**
         * <pre>
         * Informa o nome do grupo, se a mensagem for para um grupo
         * </pre>
         *
         * <code>string group = 4;</code>
         * 
         * @return The bytes for group.
         */
        com.google.protobuf.ByteString getGroupBytes();

        /**
         * <code>.Content content = 5;</code>
         * 
         * @return Whether the content field is set.
         */
        boolean hasContent();

        /**
         * <code>.Content content = 5;</code>
         * 
         * @return The content.
         */
        MessageProtoBuffer.Content getContent();

        /**
         * <code>.Content content = 5;</code>
         */
        MessageProtoBuffer.ContentOrBuilder getContentOrBuilder();
    }

    /**
     * Protobuf type {@code Message}
     */
    public static final class Message extends
            com.google.protobuf.GeneratedMessage implements
            // @@protoc_insertion_point(message_implements:Message)
            MessageOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use Message.newBuilder() to construct.
        private Message(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
        }

        private Message() {
            sender_ = "";
            date_ = "";
            hour_ = "";
            group_ = "";
        }

        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return MessageProtoBuffer.internal_static_Message_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
            return MessageProtoBuffer.internal_static_Message_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            MessageProtoBuffer.Message.class, MessageProtoBuffer.Message.Builder.class);
        }

        private int bitField0_;
        public static final int SENDER_FIELD_NUMBER = 1;
        @SuppressWarnings("serial")
        private volatile java.lang.Object sender_ = "";

        /**
         * <pre>
         * Nome do emissor
         * </pre>
         *
         * <code>string sender = 1;</code>
         * 
         * @return The sender.
         */
        @java.lang.Override
        public java.lang.String getSender() {
            java.lang.Object ref = sender_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                sender_ = s;
                return s;
            }
        }

        /**
         * <pre>
         * Nome do emissor
         * </pre>
         *
         * <code>string sender = 1;</code>
         * 
         * @return The bytes for sender.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString getSenderBytes() {
            java.lang.Object ref = sender_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
                sender_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int DATE_FIELD_NUMBER = 2;
        @SuppressWarnings("serial")
        private volatile java.lang.Object date_ = "";

        /**
         * <pre>
         * Data de envio
         * </pre>
         *
         * <code>string date = 2;</code>
         * 
         * @return The date.
         */
        @java.lang.Override
        public java.lang.String getDate() {
            java.lang.Object ref = date_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                date_ = s;
                return s;
            }
        }

        /**
         * <pre>
         * Data de envio
         * </pre>
         *
         * <code>string date = 2;</code>
         * 
         * @return The bytes for date.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString getDateBytes() {
            java.lang.Object ref = date_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
                date_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int HOUR_FIELD_NUMBER = 3;
        @SuppressWarnings("serial")
        private volatile java.lang.Object hour_ = "";

        /**
         * <pre>
         * Hora de envio
         * </pre>
         *
         * <code>string hour = 3;</code>
         * 
         * @return The hour.
         */
        @java.lang.Override
        public java.lang.String getHour() {
            java.lang.Object ref = hour_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                hour_ = s;
                return s;
            }
        }

        /**
         * <pre>
         * Hora de envio
         * </pre>
         *
         * <code>string hour = 3;</code>
         * 
         * @return The bytes for hour.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString getHourBytes() {
            java.lang.Object ref = hour_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
                hour_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int GROUP_FIELD_NUMBER = 4;
        @SuppressWarnings("serial")
        private volatile java.lang.Object group_ = "";

        /**
         * <pre>
         * Informa o nome do grupo, se a mensagem for para um grupo
         * </pre>
         *
         * <code>string group = 4;</code>
         * 
         * @return The group.
         */
        @java.lang.Override
        public java.lang.String getGroup() {
            java.lang.Object ref = group_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                group_ = s;
                return s;
            }
        }

        /**
         * <pre>
         * Informa o nome do grupo, se a mensagem for para um grupo
         * </pre>
         *
         * <code>string group = 4;</code>
         * 
         * @return The bytes for group.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString getGroupBytes() {
            java.lang.Object ref = group_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
                group_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int CONTENT_FIELD_NUMBER = 5;
        private MessageProtoBuffer.Content content_;

        /**
         * <code>.Content content = 5;</code>
         * 
         * @return Whether the content field is set.
         */
        @java.lang.Override
        public boolean hasContent() {
            return ((bitField0_ & 0x00000001) != 0);
        }

        /**
         * <code>.Content content = 5;</code>
         * 
         * @return The content.
         */
        @java.lang.Override
        public MessageProtoBuffer.Content getContent() {
            return content_ == null ? MessageProtoBuffer.Content.getDefaultInstance() : content_;
        }

        /**
         * <code>.Content content = 5;</code>
         */
        @java.lang.Override
        public MessageProtoBuffer.ContentOrBuilder getContentOrBuilder() {
            return content_ == null ? MessageProtoBuffer.Content.getDefaultInstance() : content_;
        }

        private byte memoizedIsInitialized = -1;

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1)
                return true;
            if (isInitialized == 0)
                return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sender_)) {
                com.google.protobuf.GeneratedMessage.writeString(output, 1, sender_);
            }
            if (!com.google.protobuf.GeneratedMessage.isStringEmpty(date_)) {
                com.google.protobuf.GeneratedMessage.writeString(output, 2, date_);
            }
            if (!com.google.protobuf.GeneratedMessage.isStringEmpty(hour_)) {
                com.google.protobuf.GeneratedMessage.writeString(output, 3, hour_);
            }
            if (!com.google.protobuf.GeneratedMessage.isStringEmpty(group_)) {
                com.google.protobuf.GeneratedMessage.writeString(output, 4, group_);
            }
            if (((bitField0_ & 0x00000001) != 0)) {
                output.writeMessage(5, getContent());
            }
            getUnknownFields().writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1)
                return size;

            size = 0;
            if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sender_)) {
                size += com.google.protobuf.GeneratedMessage.computeStringSize(1, sender_);
            }
            if (!com.google.protobuf.GeneratedMessage.isStringEmpty(date_)) {
                size += com.google.protobuf.GeneratedMessage.computeStringSize(2, date_);
            }
            if (!com.google.protobuf.GeneratedMessage.isStringEmpty(hour_)) {
                size += com.google.protobuf.GeneratedMessage.computeStringSize(3, hour_);
            }
            if (!com.google.protobuf.GeneratedMessage.isStringEmpty(group_)) {
                size += com.google.protobuf.GeneratedMessage.computeStringSize(4, group_);
            }
            if (((bitField0_ & 0x00000001) != 0)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(5, getContent());
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof MessageProtoBuffer.Message)) {
                return super.equals(obj);
            }
            MessageProtoBuffer.Message other = (MessageProtoBuffer.Message) obj;

            if (!getSender()
                    .equals(other.getSender()))
                return false;
            if (!getDate()
                    .equals(other.getDate()))
                return false;
            if (!getHour()
                    .equals(other.getHour()))
                return false;
            if (!getGroup()
                    .equals(other.getGroup()))
                return false;
            if (hasContent() != other.hasContent())
                return false;
            if (hasContent()) {
                if (!getContent()
                        .equals(other.getContent()))
                    return false;
            }
            if (!getUnknownFields().equals(other.getUnknownFields()))
                return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + SENDER_FIELD_NUMBER;
            hash = (53 * hash) + getSender().hashCode();
            hash = (37 * hash) + DATE_FIELD_NUMBER;
            hash = (53 * hash) + getDate().hashCode();
            hash = (37 * hash) + HOUR_FIELD_NUMBER;
            hash = (53 * hash) + getHour().hashCode();
            hash = (37 * hash) + GROUP_FIELD_NUMBER;
            hash = (53 * hash) + getGroup().hashCode();
            if (hasContent()) {
                hash = (37 * hash) + CONTENT_FIELD_NUMBER;
                hash = (53 * hash) + getContent().hashCode();
            }
            hash = (29 * hash) + getUnknownFields().hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static MessageProtoBuffer.Message parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static MessageProtoBuffer.Message parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static MessageProtoBuffer.Message parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static MessageProtoBuffer.Message parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static MessageProtoBuffer.Message parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static MessageProtoBuffer.Message parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static MessageProtoBuffer.Message parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseWithIOException(PARSER, input);
        }

        public static MessageProtoBuffer.Message parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static MessageProtoBuffer.Message parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static MessageProtoBuffer.Message parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static MessageProtoBuffer.Message parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseWithIOException(PARSER, input);
        }

        public static MessageProtoBuffer.Message parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(MessageProtoBuffer.Message prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder()
                    : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code Message}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:Message)
                MessageProtoBuffer.MessageOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
                return MessageProtoBuffer.internal_static_Message_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
                return MessageProtoBuffer.internal_static_Message_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                MessageProtoBuffer.Message.class, MessageProtoBuffer.Message.Builder.class);
            }

            // Construct using MessageProtoBuffer.Message.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                    getContentFieldBuilder();
                }
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                bitField0_ = 0;
                sender_ = "";
                date_ = "";
                hour_ = "";
                group_ = "";
                content_ = null;
                if (contentBuilder_ != null) {
                    contentBuilder_.dispose();
                    contentBuilder_ = null;
                }
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
                return MessageProtoBuffer.internal_static_Message_descriptor;
            }

            @java.lang.Override
            public MessageProtoBuffer.Message getDefaultInstanceForType() {
                return MessageProtoBuffer.Message.getDefaultInstance();
            }

            @java.lang.Override
            public MessageProtoBuffer.Message build() {
                MessageProtoBuffer.Message result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public MessageProtoBuffer.Message buildPartial() {
                MessageProtoBuffer.Message result = new MessageProtoBuffer.Message(this);
                if (bitField0_ != 0) {
                    buildPartial0(result);
                }
                onBuilt();
                return result;
            }

            private void buildPartial0(MessageProtoBuffer.Message result) {
                int from_bitField0_ = bitField0_;
                if (((from_bitField0_ & 0x00000001) != 0)) {
                    result.sender_ = sender_;
                }
                if (((from_bitField0_ & 0x00000002) != 0)) {
                    result.date_ = date_;
                }
                if (((from_bitField0_ & 0x00000004) != 0)) {
                    result.hour_ = hour_;
                }
                if (((from_bitField0_ & 0x00000008) != 0)) {
                    result.group_ = group_;
                }
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000010) != 0)) {
                    result.content_ = contentBuilder_ == null
                            ? content_
                            : contentBuilder_.build();
                    to_bitField0_ |= 0x00000001;
                }
                result.bitField0_ |= to_bitField0_;
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof MessageProtoBuffer.Message) {
                    return mergeFrom((MessageProtoBuffer.Message) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(MessageProtoBuffer.Message other) {
                if (other == MessageProtoBuffer.Message.getDefaultInstance())
                    return this;
                if (!other.getSender().isEmpty()) {
                    sender_ = other.sender_;
                    bitField0_ |= 0x00000001;
                    onChanged();
                }
                if (!other.getDate().isEmpty()) {
                    date_ = other.date_;
                    bitField0_ |= 0x00000002;
                    onChanged();
                }
                if (!other.getHour().isEmpty()) {
                    hour_ = other.hour_;
                    bitField0_ |= 0x00000004;
                    onChanged();
                }
                if (!other.getGroup().isEmpty()) {
                    group_ = other.group_;
                    bitField0_ |= 0x00000008;
                    onChanged();
                }
                if (other.hasContent()) {
                    mergeContent(other.getContent());
                }
                this.mergeUnknownFields(other.getUnknownFields());
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                if (extensionRegistry == null) {
                    throw new java.lang.NullPointerException();
                }
                try {
                    boolean done = false;
                    while (!done) {
                        int tag = input.readTag();
                        switch (tag) {
                            case 0:
                                done = true;
                                break;
                            case 10: {
                                sender_ = input.readStringRequireUtf8();
                                bitField0_ |= 0x00000001;
                                break;
                            } // case 10
                            case 18: {
                                date_ = input.readStringRequireUtf8();
                                bitField0_ |= 0x00000002;
                                break;
                            } // case 18
                            case 26: {
                                hour_ = input.readStringRequireUtf8();
                                bitField0_ |= 0x00000004;
                                break;
                            } // case 26
                            case 34: {
                                group_ = input.readStringRequireUtf8();
                                bitField0_ |= 0x00000008;
                                break;
                            } // case 34
                            case 42: {
                                input.readMessage(
                                        getContentFieldBuilder().getBuilder(),
                                        extensionRegistry);
                                bitField0_ |= 0x00000010;
                                break;
                            } // case 42
                            default: {
                                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                    done = true; // was an endgroup tag
                                }
                                break;
                            } // default:
                        } // switch (tag)
                    } // while (!done)
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.unwrapIOException();
                } finally {
                    onChanged();
                } // finally
                return this;
            }

            private int bitField0_;

            private java.lang.Object sender_ = "";

            /**
             * <pre>
             * Nome do emissor
             * </pre>
             *
             * <code>string sender = 1;</code>
             * 
             * @return The sender.
             */
            public java.lang.String getSender() {
                java.lang.Object ref = sender_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    sender_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <pre>
             * Nome do emissor
             * </pre>
             *
             * <code>string sender = 1;</code>
             * 
             * @return The bytes for sender.
             */
            public com.google.protobuf.ByteString getSenderBytes() {
                java.lang.Object ref = sender_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
                    sender_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <pre>
             * Nome do emissor
             * </pre>
             *
             * <code>string sender = 1;</code>
             * 
             * @param value The sender to set.
             * @return This builder for chaining.
             */
            public Builder setSender(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                sender_ = value;
                bitField0_ |= 0x00000001;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * Nome do emissor
             * </pre>
             *
             * <code>string sender = 1;</code>
             * 
             * @return This builder for chaining.
             */
            public Builder clearSender() {
                sender_ = getDefaultInstance().getSender();
                bitField0_ = (bitField0_ & ~0x00000001);
                onChanged();
                return this;
            }

            /**
             * <pre>
             * Nome do emissor
             * </pre>
             *
             * <code>string sender = 1;</code>
             * 
             * @param value The bytes for sender to set.
             * @return This builder for chaining.
             */
            public Builder setSenderBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);
                sender_ = value;
                bitField0_ |= 0x00000001;
                onChanged();
                return this;
            }

            private java.lang.Object date_ = "";

            /**
             * <pre>
             * Data de envio
             * </pre>
             *
             * <code>string date = 2;</code>
             * 
             * @return The date.
             */
            public java.lang.String getDate() {
                java.lang.Object ref = date_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    date_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <pre>
             * Data de envio
             * </pre>
             *
             * <code>string date = 2;</code>
             * 
             * @return The bytes for date.
             */
            public com.google.protobuf.ByteString getDateBytes() {
                java.lang.Object ref = date_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
                    date_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <pre>
             * Data de envio
             * </pre>
             *
             * <code>string date = 2;</code>
             * 
             * @param value The date to set.
             * @return This builder for chaining.
             */
            public Builder setDate(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                date_ = value;
                bitField0_ |= 0x00000002;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * Data de envio
             * </pre>
             *
             * <code>string date = 2;</code>
             * 
             * @return This builder for chaining.
             */
            public Builder clearDate() {
                date_ = getDefaultInstance().getDate();
                bitField0_ = (bitField0_ & ~0x00000002);
                onChanged();
                return this;
            }

            /**
             * <pre>
             * Data de envio
             * </pre>
             *
             * <code>string date = 2;</code>
             * 
             * @param value The bytes for date to set.
             * @return This builder for chaining.
             */
            public Builder setDateBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);
                date_ = value;
                bitField0_ |= 0x00000002;
                onChanged();
                return this;
            }

            private java.lang.Object hour_ = "";

            /**
             * <pre>
             * Hora de envio
             * </pre>
             *
             * <code>string hour = 3;</code>
             * 
             * @return The hour.
             */
            public java.lang.String getHour() {
                java.lang.Object ref = hour_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    hour_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <pre>
             * Hora de envio
             * </pre>
             *
             * <code>string hour = 3;</code>
             * 
             * @return The bytes for hour.
             */
            public com.google.protobuf.ByteString getHourBytes() {
                java.lang.Object ref = hour_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
                    hour_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <pre>
             * Hora de envio
             * </pre>
             *
             * <code>string hour = 3;</code>
             * 
             * @param value The hour to set.
             * @return This builder for chaining.
             */
            public Builder setHour(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                hour_ = value;
                bitField0_ |= 0x00000004;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * Hora de envio
             * </pre>
             *
             * <code>string hour = 3;</code>
             * 
             * @return This builder for chaining.
             */
            public Builder clearHour() {
                hour_ = getDefaultInstance().getHour();
                bitField0_ = (bitField0_ & ~0x00000004);
                onChanged();
                return this;
            }

            /**
             * <pre>
             * Hora de envio
             * </pre>
             *
             * <code>string hour = 3;</code>
             * 
             * @param value The bytes for hour to set.
             * @return This builder for chaining.
             */
            public Builder setHourBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);
                hour_ = value;
                bitField0_ |= 0x00000004;
                onChanged();
                return this;
            }

            private java.lang.Object group_ = "";

            /**
             * <pre>
             * Informa o nome do grupo, se a mensagem for para um grupo
             * </pre>
             *
             * <code>string group = 4;</code>
             * 
             * @return The group.
             */
            public java.lang.String getGroup() {
                java.lang.Object ref = group_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    group_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <pre>
             * Informa o nome do grupo, se a mensagem for para um grupo
             * </pre>
             *
             * <code>string group = 4;</code>
             * 
             * @return The bytes for group.
             */
            public com.google.protobuf.ByteString getGroupBytes() {
                java.lang.Object ref = group_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
                    group_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <pre>
             * Informa o nome do grupo, se a mensagem for para um grupo
             * </pre>
             *
             * <code>string group = 4;</code>
             * 
             * @param value The group to set.
             * @return This builder for chaining.
             */
            public Builder setGroup(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                group_ = value;
                bitField0_ |= 0x00000008;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * Informa o nome do grupo, se a mensagem for para um grupo
             * </pre>
             *
             * <code>string group = 4;</code>
             * 
             * @return This builder for chaining.
             */
            public Builder clearGroup() {
                group_ = getDefaultInstance().getGroup();
                bitField0_ = (bitField0_ & ~0x00000008);
                onChanged();
                return this;
            }

            /**
             * <pre>
             * Informa o nome do grupo, se a mensagem for para um grupo
             * </pre>
             *
             * <code>string group = 4;</code>
             * 
             * @param value The bytes for group to set.
             * @return This builder for chaining.
             */
            public Builder setGroupBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);
                group_ = value;
                bitField0_ |= 0x00000008;
                onChanged();
                return this;
            }

            private MessageProtoBuffer.Content content_;
            private com.google.protobuf.SingleFieldBuilder<MessageProtoBuffer.Content, MessageProtoBuffer.Content.Builder, MessageProtoBuffer.ContentOrBuilder> contentBuilder_;

            /**
             * <code>.Content content = 5;</code>
             * 
             * @return Whether the content field is set.
             */
            public boolean hasContent() {
                return ((bitField0_ & 0x00000010) != 0);
            }

            /**
             * <code>.Content content = 5;</code>
             * 
             * @return The content.
             */
            public MessageProtoBuffer.Content getContent() {
                if (contentBuilder_ == null) {
                    return content_ == null ? MessageProtoBuffer.Content.getDefaultInstance() : content_;
                } else {
                    return contentBuilder_.getMessage();
                }
            }

            /**
             * <code>.Content content = 5;</code>
             */
            public Builder setContent(MessageProtoBuffer.Content value) {
                if (contentBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    content_ = value;
                } else {
                    contentBuilder_.setMessage(value);
                }
                bitField0_ |= 0x00000010;
                onChanged();
                return this;
            }

            /**
             * <code>.Content content = 5;</code>
             */
            public Builder setContent(
                    MessageProtoBuffer.Content.Builder builderForValue) {
                if (contentBuilder_ == null) {
                    content_ = builderForValue.build();
                } else {
                    contentBuilder_.setMessage(builderForValue.build());
                }
                bitField0_ |= 0x00000010;
                onChanged();
                return this;
            }

            /**
             * <code>.Content content = 5;</code>
             */
            public Builder mergeContent(MessageProtoBuffer.Content value) {
                if (contentBuilder_ == null) {
                    if (((bitField0_ & 0x00000010) != 0) &&
                            content_ != null &&
                            content_ != MessageProtoBuffer.Content.getDefaultInstance()) {
                        getContentBuilder().mergeFrom(value);
                    } else {
                        content_ = value;
                    }
                } else {
                    contentBuilder_.mergeFrom(value);
                }
                if (content_ != null) {
                    bitField0_ |= 0x00000010;
                    onChanged();
                }
                return this;
            }

            /**
             * <code>.Content content = 5;</code>
             */
            public Builder clearContent() {
                bitField0_ = (bitField0_ & ~0x00000010);
                content_ = null;
                if (contentBuilder_ != null) {
                    contentBuilder_.dispose();
                    contentBuilder_ = null;
                }
                onChanged();
                return this;
            }

            /**
             * <code>.Content content = 5;</code>
             */
            public MessageProtoBuffer.Content.Builder getContentBuilder() {
                bitField0_ |= 0x00000010;
                onChanged();
                return getContentFieldBuilder().getBuilder();
            }

            /**
             * <code>.Content content = 5;</code>
             */
            public MessageProtoBuffer.ContentOrBuilder getContentOrBuilder() {
                if (contentBuilder_ != null) {
                    return contentBuilder_.getMessageOrBuilder();
                } else {
                    return content_ == null ? MessageProtoBuffer.Content.getDefaultInstance() : content_;
                }
            }

            /**
             * <code>.Content content = 5;</code>
             */
            private com.google.protobuf.SingleFieldBuilder<MessageProtoBuffer.Content, MessageProtoBuffer.Content.Builder, MessageProtoBuffer.ContentOrBuilder> getContentFieldBuilder() {
                if (contentBuilder_ == null) {
                    contentBuilder_ = new com.google.protobuf.SingleFieldBuilder<MessageProtoBuffer.Content, MessageProtoBuffer.Content.Builder, MessageProtoBuffer.ContentOrBuilder>(
                            getContent(),
                            getParentForChildren(),
                            isClean());
                    content_ = null;
                }
                return contentBuilder_;
            }

            // @@protoc_insertion_point(builder_scope:Message)
        }

        // @@protoc_insertion_point(class_scope:Message)
        private static final MessageProtoBuffer.Message DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new MessageProtoBuffer.Message();
        }

        public static MessageProtoBuffer.Message getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<Message> PARSER = new com.google.protobuf.AbstractParser<Message>() {
            @java.lang.Override
            public Message parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                Builder builder = newBuilder();
                try {
                    builder.mergeFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.setUnfinishedMessage(builder.buildPartial());
                } catch (com.google.protobuf.UninitializedMessageException e) {
                    throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
                } catch (java.io.IOException e) {
                    throw new com.google.protobuf.InvalidProtocolBufferException(e)
                            .setUnfinishedMessage(builder.buildPartial());
                }
                return builder.buildPartial();
            }
        };

        public static com.google.protobuf.Parser<Message> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<Message> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public MessageProtoBuffer.Message getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    public interface ContentOrBuilder extends
            // @@protoc_insertion_point(interface_extends:Content)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <pre>
         * Tipo do conteúdo no padrão de tipos MIME. Exemplos:
         * </pre>
         *
         * <code>string type = 1;</code>
         * 
         * @return The type.
         */
        java.lang.String getType();

        /**
         * <pre>
         * Tipo do conteúdo no padrão de tipos MIME. Exemplos:
         * </pre>
         *
         * <code>string type = 1;</code>
         * 
         * @return The bytes for type.
         */
        com.google.protobuf.ByteString getTypeBytes();

        /**
         * <pre>
         * "text/plain", "image/png"
         * </pre>
         *
         * <code>bytes body = 2;</code>
         * 
         * @return The body.
         */
        com.google.protobuf.ByteString getBody();

        /**
         * <pre>
         * Nome do conteúdo, se existente. Exemplos: "logo_ufs.png",
         * </pre>
         *
         * <code>string name = 3;</code>
         * 
         * @return The name.
         */
        java.lang.String getName();

        /**
         * <pre>
         * Nome do conteúdo, se existente. Exemplos: "logo_ufs.png",
         * </pre>
         *
         * <code>string name = 3;</code>
         * 
         * @return The bytes for name.
         */
        com.google.protobuf.ByteString getNameBytes();
    }

    /**
     * Protobuf type {@code Content}
     */
    public static final class Content extends
            com.google.protobuf.GeneratedMessage implements
            // @@protoc_insertion_point(message_implements:Content)
            ContentOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use Content.newBuilder() to construct.
        private Content(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
        }

        private Content() {
            type_ = "";
            body_ = com.google.protobuf.ByteString.EMPTY;
            name_ = "";
        }

        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return MessageProtoBuffer.internal_static_Content_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
            return MessageProtoBuffer.internal_static_Content_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            MessageProtoBuffer.Content.class, MessageProtoBuffer.Content.Builder.class);
        }

        public static final int TYPE_FIELD_NUMBER = 1;
        @SuppressWarnings("serial")
        private volatile java.lang.Object type_ = "";

        /**
         * <pre>
         * Tipo do conteúdo no padrão de tipos MIME. Exemplos:
         * </pre>
         *
         * <code>string type = 1;</code>
         * 
         * @return The type.
         */
        @java.lang.Override
        public java.lang.String getType() {
            java.lang.Object ref = type_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                type_ = s;
                return s;
            }
        }

        /**
         * <pre>
         * Tipo do conteúdo no padrão de tipos MIME. Exemplos:
         * </pre>
         *
         * <code>string type = 1;</code>
         * 
         * @return The bytes for type.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString getTypeBytes() {
            java.lang.Object ref = type_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
                type_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int BODY_FIELD_NUMBER = 2;
        private com.google.protobuf.ByteString body_ = com.google.protobuf.ByteString.EMPTY;

        /**
         * <pre>
         * "text/plain", "image/png"
         * </pre>
         *
         * <code>bytes body = 2;</code>
         * 
         * @return The body.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString getBody() {
            return body_;
        }

        public static final int NAME_FIELD_NUMBER = 3;
        @SuppressWarnings("serial")
        private volatile java.lang.Object name_ = "";

        /**
         * <pre>
         * Nome do conteúdo, se existente. Exemplos: "logo_ufs.png",
         * </pre>
         *
         * <code>string name = 3;</code>
         * 
         * @return The name.
         */
        @java.lang.Override
        public java.lang.String getName() {
            java.lang.Object ref = name_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                name_ = s;
                return s;
            }
        }

        /**
         * <pre>
         * Nome do conteúdo, se existente. Exemplos: "logo_ufs.png",
         * </pre>
         *
         * <code>string name = 3;</code>
         * 
         * @return The bytes for name.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString getNameBytes() {
            java.lang.Object ref = name_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
                name_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private byte memoizedIsInitialized = -1;

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1)
                return true;
            if (isInitialized == 0)
                return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (!com.google.protobuf.GeneratedMessage.isStringEmpty(type_)) {
                com.google.protobuf.GeneratedMessage.writeString(output, 1, type_);
            }
            if (!body_.isEmpty()) {
                output.writeBytes(2, body_);
            }
            if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
                com.google.protobuf.GeneratedMessage.writeString(output, 3, name_);
            }
            getUnknownFields().writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1)
                return size;

            size = 0;
            if (!com.google.protobuf.GeneratedMessage.isStringEmpty(type_)) {
                size += com.google.protobuf.GeneratedMessage.computeStringSize(1, type_);
            }
            if (!body_.isEmpty()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(2, body_);
            }
            if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
                size += com.google.protobuf.GeneratedMessage.computeStringSize(3, name_);
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof MessageProtoBuffer.Content)) {
                return super.equals(obj);
            }
            MessageProtoBuffer.Content other = (MessageProtoBuffer.Content) obj;

            if (!getType()
                    .equals(other.getType()))
                return false;
            if (!getBody()
                    .equals(other.getBody()))
                return false;
            if (!getName()
                    .equals(other.getName()))
                return false;
            if (!getUnknownFields().equals(other.getUnknownFields()))
                return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + TYPE_FIELD_NUMBER;
            hash = (53 * hash) + getType().hashCode();
            hash = (37 * hash) + BODY_FIELD_NUMBER;
            hash = (53 * hash) + getBody().hashCode();
            hash = (37 * hash) + NAME_FIELD_NUMBER;
            hash = (53 * hash) + getName().hashCode();
            hash = (29 * hash) + getUnknownFields().hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static MessageProtoBuffer.Content parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static MessageProtoBuffer.Content parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static MessageProtoBuffer.Content parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static MessageProtoBuffer.Content parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static MessageProtoBuffer.Content parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static MessageProtoBuffer.Content parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static MessageProtoBuffer.Content parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseWithIOException(PARSER, input);
        }

        public static MessageProtoBuffer.Content parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static MessageProtoBuffer.Content parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static MessageProtoBuffer.Content parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static MessageProtoBuffer.Content parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseWithIOException(PARSER, input);
        }

        public static MessageProtoBuffer.Content parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(MessageProtoBuffer.Content prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder()
                    : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code Content}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:Content)
                MessageProtoBuffer.ContentOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
                return MessageProtoBuffer.internal_static_Content_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
                return MessageProtoBuffer.internal_static_Content_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                MessageProtoBuffer.Content.class, MessageProtoBuffer.Content.Builder.class);
            }

            // Construct using MessageProtoBuffer.Content.newBuilder()
            private Builder() {

            }

            private Builder(
                    com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                super(parent);

            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                bitField0_ = 0;
                type_ = "";
                body_ = com.google.protobuf.ByteString.EMPTY;
                name_ = "";
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
                return MessageProtoBuffer.internal_static_Content_descriptor;
            }

            @java.lang.Override
            public MessageProtoBuffer.Content getDefaultInstanceForType() {
                return MessageProtoBuffer.Content.getDefaultInstance();
            }

            @java.lang.Override
            public MessageProtoBuffer.Content build() {
                MessageProtoBuffer.Content result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public MessageProtoBuffer.Content buildPartial() {
                MessageProtoBuffer.Content result = new MessageProtoBuffer.Content(this);
                if (bitField0_ != 0) {
                    buildPartial0(result);
                }
                onBuilt();
                return result;
            }

            private void buildPartial0(MessageProtoBuffer.Content result) {
                int from_bitField0_ = bitField0_;
                if (((from_bitField0_ & 0x00000001) != 0)) {
                    result.type_ = type_;
                }
                if (((from_bitField0_ & 0x00000002) != 0)) {
                    result.body_ = body_;
                }
                if (((from_bitField0_ & 0x00000004) != 0)) {
                    result.name_ = name_;
                }
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof MessageProtoBuffer.Content) {
                    return mergeFrom((MessageProtoBuffer.Content) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(MessageProtoBuffer.Content other) {
                if (other == MessageProtoBuffer.Content.getDefaultInstance())
                    return this;
                if (!other.getType().isEmpty()) {
                    type_ = other.type_;
                    bitField0_ |= 0x00000001;
                    onChanged();
                }
                if (other.getBody() != com.google.protobuf.ByteString.EMPTY) {
                    setBody(other.getBody());
                }
                if (!other.getName().isEmpty()) {
                    name_ = other.name_;
                    bitField0_ |= 0x00000004;
                    onChanged();
                }
                this.mergeUnknownFields(other.getUnknownFields());
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                if (extensionRegistry == null) {
                    throw new java.lang.NullPointerException();
                }
                try {
                    boolean done = false;
                    while (!done) {
                        int tag = input.readTag();
                        switch (tag) {
                            case 0:
                                done = true;
                                break;
                            case 10: {
                                type_ = input.readStringRequireUtf8();
                                bitField0_ |= 0x00000001;
                                break;
                            } // case 10
                            case 18: {
                                body_ = input.readBytes();
                                bitField0_ |= 0x00000002;
                                break;
                            } // case 18
                            case 26: {
                                name_ = input.readStringRequireUtf8();
                                bitField0_ |= 0x00000004;
                                break;
                            } // case 26
                            default: {
                                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                    done = true; // was an endgroup tag
                                }
                                break;
                            } // default:
                        } // switch (tag)
                    } // while (!done)
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.unwrapIOException();
                } finally {
                    onChanged();
                } // finally
                return this;
            }

            private int bitField0_;

            private java.lang.Object type_ = "";

            /**
             * <pre>
             * Tipo do conteúdo no padrão de tipos MIME. Exemplos:
             * </pre>
             *
             * <code>string type = 1;</code>
             * 
             * @return The type.
             */
            public java.lang.String getType() {
                java.lang.Object ref = type_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    type_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <pre>
             * Tipo do conteúdo no padrão de tipos MIME. Exemplos:
             * </pre>
             *
             * <code>string type = 1;</code>
             * 
             * @return The bytes for type.
             */
            public com.google.protobuf.ByteString getTypeBytes() {
                java.lang.Object ref = type_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
                    type_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <pre>
             * Tipo do conteúdo no padrão de tipos MIME. Exemplos:
             * </pre>
             *
             * <code>string type = 1;</code>
             * 
             * @param value The type to set.
             * @return This builder for chaining.
             */
            public Builder setType(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                type_ = value;
                bitField0_ |= 0x00000001;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * Tipo do conteúdo no padrão de tipos MIME. Exemplos:
             * </pre>
             *
             * <code>string type = 1;</code>
             * 
             * @return This builder for chaining.
             */
            public Builder clearType() {
                type_ = getDefaultInstance().getType();
                bitField0_ = (bitField0_ & ~0x00000001);
                onChanged();
                return this;
            }

            /**
             * <pre>
             * Tipo do conteúdo no padrão de tipos MIME. Exemplos:
             * </pre>
             *
             * <code>string type = 1;</code>
             * 
             * @param value The bytes for type to set.
             * @return This builder for chaining.
             */
            public Builder setTypeBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);
                type_ = value;
                bitField0_ |= 0x00000001;
                onChanged();
                return this;
            }

            private com.google.protobuf.ByteString body_ = com.google.protobuf.ByteString.EMPTY;

            /**
             * <pre>
             * "text/plain", "image/png"
             * </pre>
             *
             * <code>bytes body = 2;</code>
             * 
             * @return The body.
             */
            @java.lang.Override
            public com.google.protobuf.ByteString getBody() {
                return body_;
            }

            /**
             * <pre>
             * "text/plain", "image/png"
             * </pre>
             *
             * <code>bytes body = 2;</code>
             * 
             * @param value The body to set.
             * @return This builder for chaining.
             */
            public Builder setBody(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                body_ = value;
                bitField0_ |= 0x00000002;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * "text/plain", "image/png"
             * </pre>
             *
             * <code>bytes body = 2;</code>
             * 
             * @return This builder for chaining.
             */
            public Builder clearBody() {
                bitField0_ = (bitField0_ & ~0x00000002);
                body_ = getDefaultInstance().getBody();
                onChanged();
                return this;
            }

            private java.lang.Object name_ = "";

            /**
             * <pre>
             * Nome do conteúdo, se existente. Exemplos: "logo_ufs.png",
             * </pre>
             *
             * <code>string name = 3;</code>
             * 
             * @return The name.
             */
            public java.lang.String getName() {
                java.lang.Object ref = name_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    name_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <pre>
             * Nome do conteúdo, se existente. Exemplos: "logo_ufs.png",
             * </pre>
             *
             * <code>string name = 3;</code>
             * 
             * @return The bytes for name.
             */
            public com.google.protobuf.ByteString getNameBytes() {
                java.lang.Object ref = name_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
                    name_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <pre>
             * Nome do conteúdo, se existente. Exemplos: "logo_ufs.png",
             * </pre>
             *
             * <code>string name = 3;</code>
             * 
             * @param value The name to set.
             * @return This builder for chaining.
             */
            public Builder setName(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                name_ = value;
                bitField0_ |= 0x00000004;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * Nome do conteúdo, se existente. Exemplos: "logo_ufs.png",
             * </pre>
             *
             * <code>string name = 3;</code>
             * 
             * @return This builder for chaining.
             */
            public Builder clearName() {
                name_ = getDefaultInstance().getName();
                bitField0_ = (bitField0_ & ~0x00000004);
                onChanged();
                return this;
            }

            /**
             * <pre>
             * Nome do conteúdo, se existente. Exemplos: "logo_ufs.png",
             * </pre>
             *
             * <code>string name = 3;</code>
             * 
             * @param value The bytes for name to set.
             * @return This builder for chaining.
             */
            public Builder setNameBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);
                name_ = value;
                bitField0_ |= 0x00000004;
                onChanged();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:Content)
        }

        // @@protoc_insertion_point(class_scope:Content)
        private static final MessageProtoBuffer.Content DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new MessageProtoBuffer.Content();
        }

        public static MessageProtoBuffer.Content getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<Content> PARSER = new com.google.protobuf.AbstractParser<Content>() {
            @java.lang.Override
            public Content parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                Builder builder = newBuilder();
                try {
                    builder.mergeFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.setUnfinishedMessage(builder.buildPartial());
                } catch (com.google.protobuf.UninitializedMessageException e) {
                    throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
                } catch (java.io.IOException e) {
                    throw new com.google.protobuf.InvalidProtocolBufferException(e)
                            .setUnfinishedMessage(builder.buildPartial());
                }
                return builder.buildPartial();
            }
        };

        public static com.google.protobuf.Parser<Content> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<Content> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public MessageProtoBuffer.Content getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor internal_static_Message_descriptor;
    private static final com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_Message_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor internal_static_Content_descriptor;
    private static final com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_Content_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
    static {
        java.lang.String[] descriptorData = {
                "\n\034src/main/proto/message.proto\"_\n\007Messag" +
                        "e\022\016\n\006sender\030\001 \001(\t\022\014\n\004date\030\002 \001(\t\022\014\n\004hour\030"
                        +
                        "\003 \001(\t\022\r\n\005group\030\004 \001(\t\022\031\n\007content\030\005 \001(\0132\010." +
                        "Content\"3\n\007Content\022\014\n\004type\030\001 \001(\t\022\014\n\004body" +
                        "\030\002 \001(\014\022\014\n\004name\030\003 \001(\tB\024B\022MessageProtoBuff" +
                        "erb\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[] {
                        });
        internal_static_Message_descriptor = getDescriptor().getMessageTypes().get(0);
        internal_static_Message_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_Message_descriptor,
                new java.lang.String[] { "Sender", "Date", "Hour", "Group", "Content", });
        internal_static_Content_descriptor = getDescriptor().getMessageTypes().get(1);
        internal_static_Content_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_Content_descriptor,
                new java.lang.String[] { "Type", "Body", "Name", });
        descriptor.resolveAllFeaturesImmutable();
    }

    // @@protoc_insertion_point(outer_class_scope)
}
